#!/usr/bin/env node
/**
 * Proxy Subpath Regression Tests
 *
 * THE BUG (2026-05-05):
 *   Storefront cart drawer didn't load. fetch('/apps/eliminai-cart/config') returned 404.
 *   Root cause: another app (old "Eliminai Smart Cart") was holding the `eliminai-cart`
 *   subpath. When the new "Eliminai Cart Drawer" app installed, Shopify auto-renamed
 *   its proxy subpath to `eliminai-cart-1`. The Liquid embed and v14-complete.js still
 *   fetched `/apps/eliminai-cart/...` (toml's intended subpath), but Shopify routed
 *   that path to the OTHER app's backend, which 404'd.
 *
 * LOCKS — These prevent the bug from reappearing:
 *   1. STATIC: shopify.app.toml subpath, Liquid PROXY_PATH, and v14-complete.js
 *      hardcoded URLs must all agree on the same subpath.
 *   2. STATIC: backend has a route at /api/proxy/config that handles the request.
 *   3. LIVE (run with --live): hitting https://<test-store>/apps/<subpath>/config
 *      returns 200 JSON with `cartConfig`. Catches Shopify-side subpath rename
 *      (the actual failure mode that occurred — static tests cannot detect it).
 *
 * Usage:
 *   node tests/proxy-subpath.test.js              # static checks only
 *   node tests/proxy-subpath.test.js --live       # also probe the live test store
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const isLive = args.includes('--live');

let passed = 0;
let failed = 0;
const failures = [];

function test(name, fn) {
  return Promise.resolve()
    .then(() => fn())
    .then(() => {
      passed++;
      console.log('  \u2713 ' + name);
    })
    .catch((err) => {
      failed++;
      failures.push({ name: name, error: err.message });
      console.log('  \u2717 ' + name);
      console.log('    ' + err.message);
    });
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function assertEq(actual, expected, message) {
  if (actual !== expected) {
    throw new Error(message + '\n    expected: ' + JSON.stringify(expected) + '\n    actual:   ' + JSON.stringify(actual));
  }
}

const ROOT = path.resolve(__dirname, '..');

function readFile(rel) {
  return fs.readFileSync(path.join(ROOT, rel), 'utf8');
}

// Parse subpath from shopify.app.toml — single source of truth.
function getTomlSubpath() {
  const toml = readFile('shopify.app.toml');
  const m = toml.match(/^\s*subpath\s*=\s*"([^"]+)"\s*$/m);
  if (!m) throw new Error('shopify.app.toml has no subpath line');
  return m[1];
}

// Parse PROXY_PATH from app-embed.liquid.
function getLiquidProxyPath() {
  const liquid = readFile('extensions/cart-drawer/blocks/app-embed.liquid');
  const m = liquid.match(/var\s+PROXY_PATH\s*=\s*'([^']+)'/);
  if (!m) throw new Error('app-embed.liquid has no PROXY_PATH var');
  return m[1];
}

// Find every hardcoded /apps/<something> reference in a JS file.
function getJsHardcodedSubpaths(rel) {
  const code = readFile(rel);
  const re = /['"`]\/apps\/([a-z0-9-]+)\/[a-z0-9-]+['"`]/g;
  const found = new Set();
  let m;
  while ((m = re.exec(code)) !== null) {
    found.add(m[1]);
  }
  return Array.from(found);
}

async function run() {
  console.log('\nProxy Subpath Regression Tests');
  console.log('='.repeat(60));

  let tomlSubpath;

  // ================================================================
  // STATIC LOCKS
  // ================================================================

  await test('shopify.app.toml declares an [app_proxy] subpath', () => {
    tomlSubpath = getTomlSubpath();
    assert(tomlSubpath && tomlSubpath.length > 0, 'subpath must be non-empty');
    // Sanity: subpath must be URL-safe lowercase
    assert(/^[a-z0-9-]+$/.test(tomlSubpath), 'subpath must be lowercase URL-safe: ' + tomlSubpath);
  });

  await test('app-embed.liquid PROXY_PATH matches toml subpath', () => {
    const liquidPath = getLiquidProxyPath();
    const expected = '/apps/' + tomlSubpath + '/config';
    assertEq(liquidPath, expected, 'Liquid PROXY_PATH drifted from toml subpath');
  });

  await test('root v14-complete.js hardcodes ONLY the toml subpath', () => {
    const found = getJsHardcodedSubpaths('v14-complete.js');
    assert(found.length > 0, 'v14-complete.js must reference /apps/<subpath>/... at least once');
    for (const sp of found) {
      assertEq(sp, tomlSubpath,
        'v14-complete.js references /apps/' + sp + '/... — must match toml subpath /apps/' + tomlSubpath + '/...');
    }
  });

  await test('extension v14-complete.js hardcodes ONLY the toml subpath', () => {
    const rel = 'extensions/cart-drawer/assets/v14-complete.js';
    if (!fs.existsSync(path.join(ROOT, rel))) {
      // Extension copy is generated by deploy script; if missing, skip
      return;
    }
    const found = getJsHardcodedSubpaths(rel);
    assert(found.length > 0, 'extension v14-complete.js must reference /apps/<subpath>/...');
    for (const sp of found) {
      assertEq(sp, tomlSubpath,
        'extension v14-complete.js references /apps/' + sp + '/... — must match toml /apps/' + tomlSubpath + '/...');
    }
  });

  await test('backend route /api/proxy/config exists', () => {
    const rel = 'backend/src/app/api/proxy/config/route.ts';
    assert(fs.existsSync(path.join(ROOT, rel)), 'Backend config route file missing: ' + rel);
  });

  await test('backend route /api/proxy/event exists (used by v14-complete.js telemetry)', () => {
    const rel = 'backend/src/app/api/proxy/event/route.ts';
    assert(fs.existsSync(path.join(ROOT, rel)), 'Backend event route file missing: ' + rel);
  });

  await test('app-embed.liquid loads v14-complete.js after fetching config', () => {
    const liquid = readFile('extensions/cart-drawer/blocks/app-embed.liquid');
    // Must store the JS asset URL on CCD_CONFIG._jsUrl OR build a script tag with v14-complete.js
    assert(
      liquid.includes("'v14-complete.js'") || liquid.includes('v14-complete.js'),
      'app-embed.liquid must reference v14-complete.js asset'
    );
    // Must POST to the proxy path before loading the JS
    assert(liquid.includes('PROXY_PATH'), 'app-embed.liquid must use PROXY_PATH constant');
    assert(/fetch\s*\(\s*PROXY_PATH/.test(liquid), 'app-embed.liquid must fetch(PROXY_PATH, ...)');
  });

  // ================================================================
  // LIVE LOCK — only with --live (catches Shopify-side rename)
  // This is the test that would have caught the 2026-05-05 bug.
  // ================================================================
  if (isLive) {
    const TEST_STORE = process.env.PROXY_TEST_STORE || 'eliminai-test.myshopify.com';
    const STORE_PASSWORD = process.env.PROXY_TEST_STORE_PASSWORD || '';

    // If the store has password protection, get a storefront_digest cookie first.
    // Without it, Shopify 302's all unauthenticated traffic to /password and we
    // can't distinguish "proxy subpath renamed" from "store is locked".
    async function getAuthCookie() {
      if (!STORE_PASSWORD) return '';
      const form = new URLSearchParams();
      form.set('form_type', 'storefront_password');
      form.set('utf8', '\u2713');
      form.set('password', STORE_PASSWORD);
      const auth = await fetch('https://' + TEST_STORE + '/password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: form.toString(),
        redirect: 'manual',
      });
      const setCookie = auth.headers.get('set-cookie') || '';
      const m = setCookie.match(/storefront_digest=[^;]+/);
      if (!m) throw new Error('Could not get storefront_digest cookie — PROXY_TEST_STORE_PASSWORD may be wrong');
      return m[0];
    }

    await test('LIVE: /apps/<subpath>/config returns 200 JSON with cartConfig on ' + TEST_STORE, async () => {
      const cookie = await getAuthCookie();
      const url = 'https://' + TEST_STORE + '/apps/' + tomlSubpath + '/config';
      const headers = { 'Content-Type': 'application/json' };
      if (cookie) headers['Cookie'] = cookie;
      const res = await fetch(url, {
        method: 'POST',
        headers: headers,
        redirect: 'manual',
        body: JSON.stringify({
          sessionToken: 'regression-test-' + Date.now(),
          deviceType: 'DESKTOP',
          isReturning: false,
          visitCount: 1,
          hasCustomerId: false,
          themeId: null,
          prefetch: true,
        }),
      });

      // If we got bounced to /password, the store is locked and we don't have a working password.
      if (res.status === 302 && (res.headers.get('location') || '').includes('/password')) {
        throw new Error(
          'Store ' + TEST_STORE + ' is password-protected. ' +
          'Set PROXY_TEST_STORE_PASSWORD env var to the storefront password so this test can authenticate. ' +
          'Without it, the test cannot distinguish a proxy subpath rename from a locked store.'
        );
      }

      assertEq(res.status, 200,
        'Proxy returned ' + res.status + ' from ' + url +
        ' — Shopify likely renamed the subpath (e.g. eliminai-cart-1) due to a collision with another app. ' +
        'Check Shopify admin → Settings → Apps → Eliminai Cart Drawer → App Proxy URL.');

      const ct = res.headers.get('content-type') || '';
      assert(ct.includes('application/json'),
        'Expected JSON content-type, got "' + ct + '" — proxy likely fell through to a different handler');

      const body = await res.json();
      assert(body && typeof body === 'object', 'Response body must be an object');
      assert(body.cartConfig, 'Response must include cartConfig field — got keys: ' + Object.keys(body || {}).join(','));
      assert(typeof body.sessionId === 'string' && body.sessionId.length > 0,
        'Response must include a non-empty sessionId');
    });
  } else {
    console.log('  \u26a0  Skipping LIVE proxy probe — run with --live to verify Shopify subpath registration');
  }

  // ================================================================
  // RESULTS
  // ================================================================
  console.log('\n' + '='.repeat(60));
  console.log('Proxy Subpath: ' + passed + ' passed, ' + failed + ' failed, ' + (passed + failed) + ' total');

  if (failed > 0) {
    console.log('\nFAILED:');
    failures.forEach(function (f) {
      console.log('  \u2717 ' + f.name);
      console.log('    ' + f.error);
    });
    console.log('\n\u26a0\ufe0f  PROXY SUBPATH REGRESSION DETECTED \u2014 cart drawer will be broken on storefront!');
    process.exit(1);
  } else {
    console.log('\n\u2713 All proxy subpath checks pass');
    process.exit(0);
  }
}

run().catch(function (e) {
  console.error('Proxy subpath test error:', e);
  process.exit(1);
});
